---

- name: install mariadb related packages
  package:
    name: '{{ mariadb_packages }}'
    state: present
  notify:
    - 'mariadb restart daemon'
    - 'mariadb remove anonymous users'
    - 'mariadb remove test database'

- name: create mariadb configuration directory
  file:
    path: '{{ mariadb_conf_dir }}'
    owner: root
    group: root
    mode: 0755
    state: directory
    seuser: system_u
    serole: object_r
    setype: mysqld_etc_t
    selevel: s0

- name: remove stub configurations
  file:
    path: '{{ item }}'
    state: absent
  with_items: '{{ mariadb_conf_remove }}'
  when: mariadb_conf_remove is defined and
        item is defined and item
